Add protocol field to WebSocket
tokio-rs/axum pull request #1022
Opened 2022-05-10 18:13 UTC by MatteoJoliveau

Signed-off-by: Matteo Joliveau <matteojoliveau@gmail.com>

Closes #1020 

I used `String::from_utf8_lossy` because I didn't want to add complex error handling for a corner case (non-UTF8 characters in an HTTP header) that, for this particular use-case, is pretty rare. I would have loved to use a `Cow` instead of a `String` inside of `WebSocket` to avoid an allocation, but I had a bit of a hard time fighting with lifetimes so I eventually conceded.

Feedbacks and suggestions welcome!

2022-05-10 19:02 UTC, davidpdrsn requested changes

2022-05-10 19:02 UTC, davidpdrsn commented on axum/src/extract/ws.rs
> +    pub fn protocol(&self) -> Option<&str> {
I think we should just return `&HeaderValue` and let the user deal with whether they care about non utf-8 or not.

2022-05-10 20:27 UTC, jplatte commented on axum/src/extract/ws.rs
> +    /// Return the selected WebSocket subprotocol, if one has been chosen
```suggestion
    /// Return the selected WebSocket subprotocol, if one has been chosen.
```

2022-05-11 07:54 UTC, davidpdrsn reviewed
Nice!

Wanna update the changelog as well?

2022-05-11 07:57 UTC, jplatte approved these changes

2022-05-11 08:15 UTC, MatteoJoliveau commented
@davidpdrsn changelog updated!

2022-05-11 08:35 UTC, davidpdrsn approved these changes

2022-05-11 08:35 UTC, davidpdrsn commented
Thanks!

2022-05-11 08:49 UTC, merged