Avoid double-boxing bodies where possible
tokio-rs/axum pull request #569
Opened 2021-11-26 18:14 UTC by KaiJewson

## Motivation

It can be inefficient if bodies are accidentally boxed twice - for example a handler might return a `Response<BoxBody>`, which `MethodRouter` would then box again.

## Solution

Ensure that bodies don't get boxed twice, by checking if they are already boxed and if so not doing anything.

2021-11-26 18:52 UTC, KaiJewson commented
Hmm, with this change might it be possible to modify `IntoResponse` to always return `BoxBody`? Since it will probably be boxed anyway somewhere down the line there would only be a performance difference in a tiny handful of cases. Doing so would drastically simplify lots of generic code I'm currently writing, so I think it would be quite nice. The original motivation for making `IntoResponse` have associated types was back when it returned the less general `hyper::Body` type, but now `BoxBody` exists that motivation isn't present anymore.

2021-11-26 21:24 UTC, davidpdrsn requested changes

2021-11-26 21:24 UTC, davidpdrsn commented on axum/src/body/mod.rs
> +}
We already have [this](https://github.com/tokio-rs/axum/blob/main/axum/src/routing/mod.rs#L660-L672) which does the same thing. Maybe we could move that to the root module and re-use it?

2021-11-26 21:24 UTC, davidpdrsn commented on axum/src/body/mod.rs
> +/// If the given body is already a [`BoxBody`], this function will not box the body again.
Hm this feels like an implementation detail thats probably not worth documenting 🤔

2021-11-26 21:25 UTC, davidpdrsn commented
Nice!

> Since it will probably be boxed anyway somewhere down the line there would only be a performance difference in a tiny handful of cases. Doing so would drastically simplify lots of generic code I'm currently writing, so I think it would be quite nice.

Wanna elaborate on this? I personally think being able to return any body type is quite ergonomic.

2021-11-26 22:28 UTC, KaiJewson commented
> Wanna elaborate on this? I personally think being able to return any body type is quite ergonomic. Its also one less than we'd have to explain to users.

My idea was to change the definition of `IntoResponse` to this:

```rs
pub trait IntoResponse: Sized {
    fn into_response(self) -> Response<BoxBody>;
}
```

The types `IntoResponse` would be implemented for wouldn't change at all, and we also wouldn't lose any flexibility because the trait bounds required to implement it would be the exact same. Its main benefit is allowing this code to just compile:

```rs
async fn index() -> impl IntoResponse {
    if condition() {
        "hello world".into_response()
    } else {
        ().into_response()
    }
}
```

It currently doesn't because the body types are different and I find that annoying - I can always box myself, but if Axum did that automatically it would be easier, and with this PR not any less fast.

2021-11-27 09:19 UTC, davidpdrsn commented
Ah yes I see. Not quite sure how I feel about it but definitely worth exploring for 0.4. Do wanna file an issue about that?

2021-11-27 09:20 UTC, davidpdrsn approved these changes

2021-11-27 09:20 UTC, merged