Httpbody
tokio-rs/axum pull request #624
Opened 2021-12-13 15:41 UTC by lz1998

## Motivation
Replace `http_body::{Body, Empty, Full}` with `crate::body::{HttpBody, Empty, Full}`

Replace `bytes::Bytes` with `crate::body::Bytes`

## Solution
replace

2021-12-13 15:56 UTC, jplatte approved these changes
LGTM 👍🏼

2021-12-13 21:29 UTC, davidpdrsn requested changes

2021-12-13 21:29 UTC, davidpdrsn commented on axum/src/routing/method_routing.rs
> +            ResBody: crate::body::HttpBody<Data = Bytes> + Send + 'static,
```suggestion
            ResBody: HttpBody<Data = Bytes> + Send + 'static,
```

2021-12-13 21:29 UTC, davidpdrsn commented on axum/src/routing/method_routing.rs
> +            ResBody: crate::body::HttpBody<Data = Bytes> + Send + 'static,
```suggestion
            ResBody: HttpBody<Data = Bytes> + Send + 'static,
```

2021-12-14 08:16 UTC, davidpdrsn approved these changes

2021-12-14 09:08 UTC, lz1998 commented
What should I do to pass this check? I didn't modify cargo.toml. It seems strange.

https://github.com/tokio-rs/axum/runs/4517160809?check_suite_focus=true

```bash
error[B004]: found 2 duplicate entries for crate 'itoa'
   ┌─ /github/workspace/Cargo.lock:58:1
   │  
58 │ ╭ itoa 0.4.8 registry+https://github.com/rust-lang/crates.io-index
59 │ │ itoa 1.0.1 registry+https://github.com/rust-lang/crates.io-index
   │ ╰────────────────────────────────────────────────────────────────^ lock entries
   │  
   = itoa v0.4.8
     ├── http v0.2.5
     │   ├── axum v0.4.2
     │   │   └── (dev) axum-core v0.1.1
     │   │       └── axum v0.4.2 (*)
     │   ├── axum-core v0.1.1 (*)
     │   ├── h2 v0.3.9
     │   │   └── hyper v0.14.16
     │   │       ├── axum v0.4.2 (*)
     │   │       ├── (dev) axum-core v0.1.1 (*)
     │   │       ├── hyper-rustls v0.23.0
     │   │       │   └── reqwest v0.11.7
     │   │       │       └── (dev) axum v0.4.2 (*)
     │   │       └── reqwest v0.11.7 (*)
     │   ├── headers v0.3.5
     │   │   └── axum v0.4.2 (*)
     │   ├── headers-core v0.2.0
     │   │   └── headers v0.3.5 (*)
     │   ├── http-body v0.4.4
     │   │   ├── axum v0.4.2 (*)
     │   │   ├── axum-core v0.1.1 (*)
     │   │   ├── hyper v0.14.16 (*)
     │   │   ├── reqwest v0.11.7 (*)
     │   │   └── tower-http v0.2.0
     │   │       ├── (dev) axum v0.4.2 (*)
     │   │       └── axum v0.4.2 (*)
     │   ├── hyper v0.14.16 (*)
     │   ├── hyper-rustls v0.23.0 (*)
     │   ├── multer v2.0.1
     │   │   └── axum v0.4.2 (*)
     │   ├── reqwest v0.11.7 (*)
     │   ├── tower-http v0.2.0 (*)
     │   └── tungstenite v0.16.0
     │       └── tokio-tungstenite v0.16.1
     │           └── axum v0.4.2 (*)
     ├── hyper v0.14.16 (*)
     └── serde_urlencoded v0.7.0
         ├── axum v0.4.2 (*)
         └── reqwest v0.11.7 (*)
   = itoa v1.0.1
     └── serde_json v1.0.73
         ├── (dev) axum v0.4.2
         │   └── (dev) axum-core v0.1.1
         │       └── axum v0.4.2 (*)
         ├── axum v0.4.2 (*)
         ├── reqwest v0.11.7
         │   └── (dev) axum v0.4.2 (*)
         └── reqwest v0.11.7 (*)

warning[L003]: encoding_rs = 0.8.30 is unlicensed
  ┌─ encoding_rs 0.8.30 (registry+https://github.com/rust-lang/crates.io-index):2:9
  │
2 │ name = "encoding_rs"
  │         ^^^^^^^^^^^ a valid license expression could not be retrieved for the crate
3 │ version = "0.8.30"
4 │ license = ""
  │            - license expression was not specified
5 │ license-files = [
6 │     { path = "COPYRIGHT", hash = 0x39f8ad31, score = 0.14 },
  │                                                      ---- low confidence in the license text
  │
  = encoding_rs v0.8.30
    ├── multer v2.0.1
    │   └── axum v0.4.2
    │       └── (dev) axum-core v0.1.1
    │           └── axum v0.4.2 (*)
    └── reqwest v0.11.7
        └── (dev) axum v0.4.2 (*)

warning[L002]: license requirements satisfied
  ┌─ webpki-roots 0.21.1 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            accepted: license is considered copyleft
  │
  = webpki-roots v0.21.1
    └── reqwest v0.11.7
        └── (dev) axum v0.4.2
            └── (dev) axum-core v0.1.1
                └── axum v0.4.2 (*)

bans FAILED, licenses ok, sources ok
```

2021-12-14 09:57 UTC, jplatte commented
This is unrelated to your PR. I think there's an ignore section for duplicate dependencies in `deny.toml` where you can add itoa.

2021-12-14 10:20 UTC, davidpdrsn commented
I'm gonna file a separate PR to fix this on CI.

2021-12-14 11:01 UTC, davidpdrsn commented
@lz1998 merging latest `main` should fix it.

2021-12-14 11:36 UTC, lz1998 commented
> @lz1998 merging latest `main` should fix it.

I have rebased to latest `main`.

2021-12-14 11:58 UTC, merged

2021-12-14 11:58 UTC, davidpdrsn commented
Thanks!