Fix trailing redirection with query parameters
tokio-rs/axum pull request #936
Opened 2022-04-16 03:52 UTC by calavera

## Motivation

When the request URI matches a route that need a trailing slash, or has an extra trailing slash, the redirect URI is not generated correctly.

This change adds or removes a trailing slash to the path part of the URI, instead of the full URI, preserving query parameters during redirection.

2022-04-16 10:14 UTC, jplatte reviewed
`str::replace` replaces all matches of a pattern, so `/foo?bar=/foo` would get rewritten to `/foo/?bar=/foo/`. Please use something like `.find('?')` + `.insert(idx, '/')` instead.

2022-04-16 11:25 UTC, davidpdrsn commented
There are also methods to take apart the path and query. Can't quite put it back together as easily but I think that's safer to use. We do that already in `StripPrefix` afaik.

2022-04-16 16:14 UTC, calavera commented
@jplatte, @davidpdrsn I've updated it to make it safer

2022-04-17 08:14 UTC, davidpdrsn requested changes
Thanks for noticing this! I had one minor comment.

2022-04-17 08:14 UTC, davidpdrsn commented on axum/src/routing/mod.rs
> +    parts.path_and_query = new_path_and_query.parse().ok();
Feels to me like this should be an `unwrap`

```suggestion
    parts.path_and_query = new_path_and_query.parse().unwrap();
```

2022-04-17 16:46 UTC, calavera commented
> Thanks for noticing this! I had one minor comment.

Updated

2022-04-17 21:06 UTC, davidpdrsn approved these changes

2022-04-17 21:12 UTC, merged