Add `FromExtractor` and deprecate `extractor_middleware`
tokio-rs/axum pull request #957
Opened 2022-04-22 14:54 UTC by arniu

## Motivation

## Solution

2022-04-22 15:08 UTC, jplatte requested changes
You seem to have run some formatting on the changelog, please undo those (unrelated) changes.

Also, in addition to the function, the layer and response future type are also part of the public API and need to stay accessible under their old paths / names (as re-exports) to maintain backwards compatibility.

2022-04-23 08:19 UTC, jplatte approved these changes

2022-04-24 11:15 UTC, davidpdrsn requested changes
Thanks!

Wanna add an `#[allow(deprecated)]` to `axum/src/extract/mod.rs` to fix the warnings shown in GitHub?

2022-04-24 11:15 UTC, davidpdrsn commented on axum/src/extract/extractor_middleware.rs
> +/// Deprecated, please use [`crate::middleware::from_extractor`] instead
This note is shown in the generated docs as well so we can probably just remove it. Its a bit redundant now.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/718941/164973702-d275e26e-90b9-4b4e-8a09-508b2f9ed96d.png">

2022-04-24 15:26 UTC, davidpdrsn approved these changes

2022-04-24 15:31 UTC, merged